### ISSUE TITLE
Light Themes? 👀

### ISSUE THREAD

**Issue by EmranMR** [TeriyakiBomb/Ashokai#1]
Hi Ash! 
Thank you for the theme, I have always wanted a fusion of these two theme! The contrast is crisp, and way more semantic than most themes out there, maybe it was because most were not PHP Laravel etc.
 
I know the theming selectors has been way more  superior for Catppuccin but I always used Monokai for the bang on colour scheme.

Only thing missing is light theme?

I have been using this version of [Monokai Pro](https://github.com/keisto/Monokai-Pro.novaextension) since early days of Nova. The idea is great and the two new Light themes have great colour combo (warm being my fav!).
However NOT the best and I think the development has stopped? Can you do your magic and mash up two light themes inspired by the cream and the white? 

Current issues I have noticed with those theme, that bugged me for years:
- The contrast is **not** the best with these themes. If you use the inspector you will see the errors. 
- Semantics, and theme selectors are not the best, everything is coloured red.. 😬 I believe that was one of the main reason inspired you to make your own. If you open a blade file all is red.

**Comment by TeriyakiBomb** [comment]
Hiya Emran, thank you for the kind words!

You're a mind reader. The entire reason for making Ashokai was the highlight inconsistency in Monokai pro and the lack of contrast :) 

I've actually been slowly playing with ideas for an Ashokai light theme, I haven't gotten the contrast and legibility quite right yet though. I'll start committing some ideas to the repo so you can take a look.

Big fan of Laravel suite, you should take a look at the artisan extension I recently released, you might like it ;) nova://extension/?id=teriyaki.LaravelArtisan&name=Laravel%20Artisan

**Comment by TeriyakiBomb** [comment]
Hey, I've added one of the light themes I've been working on, so feel free to have a look and feed back, it's close-ish to the Monokai warm theme

**Comment by EmranMR** [comment]
> Big fan of Laravel suite, you should take a look at the artisan extension I recently released, you might like it ;) nova://extension/?id=teriyaki.LaravelArtisan&name=Laravel%20Artisan

I think I was one of a first ones who downloaded/starred the artisan extension! Big fan of your work as well @TeriyakiBomb . Please keep up the amazing work! 🙏

I personally believe Nova has potential to be the best Laravel Dev Suite. we just have to gradually build the ecosystem!
The artisan was one of the features I was hoping to add at some point in the future but I am glad you managed to sort it out!💪

Hopefully I find some time to work on some other features as well soon 😬! Still plenty of other things to be added! 

I am going to of close the issue because you have already thought about everything anyways, not to mention the new release! I can't wait to try it, as soon as I get back to my workstation!
