### ISSUE TITLE
String RegEx in JS files

### ISSUE THREAD

**Issue by EmranMR** [TeriyakiBomb/Ashokai#2]
Hi @TeriyakiBomb!
I hope all is well, and thanks again for the light version, I have officially migrated to Ashokai! haha
So, not sure how this pans out for other languages, but in JS, there is a bit of a contrast issue, not only with the background but also with the property identifiers surrounding RegEx and String. I have attached a sample here from inside an object in JS. 

Again I am no designer and not sure what would be the best, but I think maybe a complimentary royal dark green would be a better option, maybe a tad lighter or darker whatever that matches the creamy background?? 

I would love to hear your take on this! tbh making themes are easier said than done, very difficult to hit the nail!

Thanks
Emran

 
<img width="723" alt="Screenshot 2023-11-21 at 13 09 02" src="https://github.com/TeriyakiBomb/Ashokai/assets/11975985/13cd67ab-50bb-43c8-b5fc-433ab787f73c">

**Comment by TeriyakiBomb** [comment]
Yeah, I had my eye on this. Light mode is hard when you're trying to keep it close to a dark theme!

I've switched it out with an existing green from the palette, kinda expected to do something like this already, good to have it validated.

Updated in Nova.
